// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDylpxZjkL3E0eV21W9oA8hr3XBMlR0H4c',
    appId: '1:592830038461:web:1aa0b9b76f3c246ea352d4',
    messagingSenderId: '592830038461',
    projectId: 'mynotes-flutter-project-first',
    authDomain: 'mynotes-flutter-project-first.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-first.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB33hazIf1pRfyG-k6eQMmGt5IyyZp5vT4',
    appId: '1:592830038461:android:90610c959135e622a352d4',
    messagingSenderId: '592830038461',
    projectId: 'mynotes-flutter-project-first',
    storageBucket: 'mynotes-flutter-project-first.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh_VXOHzZQnwJRpIfNSwKfYA2FGggWWeQ',
    appId: '1:592830038461:ios:b174e8bf1bab2e00a352d4',
    messagingSenderId: '592830038461',
    projectId: 'mynotes-flutter-project-first',
    storageBucket: 'mynotes-flutter-project-first.appspot.com',
    iosClientId: '592830038461-86nj2b5ad6jad1o3noblkogvoe628vjp.apps.googleusercontent.com',
    iosBundleId: 'com.flut.firstapp',
  );
}
